name: Deploy featurevisor

on: [push]

env:
  BRANCH_NAME: ${{ github.ref_name }}
permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Netlify
        run: npm install netlify-cli@17.19.0 -g

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Git configs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Version
        run: npm version patch

      - name: Build project
        run: npm run build

      - name: Test specs
        run: npm test

      - name: Push back to origin
        run: |
            git add .featurevisor/*
            git commit --amend --no-edit
            git push

      - name: Generate status site
        run: npm run export

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
            prod_flag=""
            if [ "$BRANCH_NAME" = "master" ]; then prod_flag="--prod"; fi
            netlify deploy \
            --dir out \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            $prod_flag 
